# Generated by Django 6.0.8 on 2026-08-05 18:16

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('topic_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Topic Title Denormalized')),
                ('course_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Course Code Denormalized')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('option_a', models.TextField(verbose_name='Option A')),
                ('option_b', models.TextField(verbose_name='Option B')),
                ('option_c', models.TextField(verbose_name='Option C')),
                ('option_d', models.TextField(verbose_name='Option D')),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=5, verbose_name='Correct Answer')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explanation')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=20, verbose_name='Difficulty')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('is_free_trial', models.BooleanField(db_index=True, default=False, verbose_name='Is Free Trial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'is_active'], name='questions_q_course__808248_idx'), models.Index(fields=['topic', 'is_active'], name='questions_q_topic_i_ad798a_idx'), models.Index(fields=['is_free_trial', 'is_active'], name='questions_q_is_free_3589c3_idx')],
            },
        ),
    ]
