# Generated by Django 6.0.8 on 2026-08-05 18:16

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Department Name')),
                ('level', models.CharField(db_index=True, default='100', max_length=20, verbose_name='Academic Level')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Address')),
                ('profile_image', models.TextField(blank=True, default='', verbose_name='Profile Image URL')),
                ('my_referral_code', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='My Referral Code')),
                ('referral_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Referred By Code')),
                ('is_activated', models.BooleanField(db_index=True, default=False, verbose_name='Is Account Activated')),
                ('activation_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Activation Code Used')),
                ('activation_date', models.DateTimeField(blank=True, null=True, verbose_name='Activation Date')),
                ('access_expires', models.DateTimeField(blank=True, null=True, verbose_name='Access Expiration Date')),
                ('free_trial_used', models.BooleanField(default=False, verbose_name='Free Trial Used')),
                ('total_questions_answered', models.PositiveIntegerField(default=0, verbose_name='Total Questions Answered')),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name='Total Correct Answers')),
                ('total_practice_sessions', models.PositiveIntegerField(default=0, verbose_name='Total Practice Sessions')),
                ('total_mock_exams', models.PositiveIntegerField(default=0, verbose_name='Total Mock Exams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
