# Generated by Django 6.0.8 on 2026-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE students_studentprofile "
                        "ALTER COLUMN free_trial_used TYPE jsonb "
                        "USING to_jsonb(free_trial_used)"
                    ),
                    reverse_sql=(
                        "ALTER TABLE students_studentprofile "
                        "ALTER COLUMN free_trial_used TYPE boolean "
                        "USING free_trial_used::boolean"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='studentprofile',
                    name='free_trial_used',
                    field=models.JSONField(blank=True, default=dict, verbose_name='Free Trial Used'),
                ),
            ],
        ),
    ]
