# Generated by Django 6.0.8 on 2026-08-05 18:16

import common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Department Name Override')),
                ('title', models.CharField(max_length=255, verbose_name='Course Title')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Course Code')),
                ('level', models.CharField(db_index=True, default='100', max_length=20, verbose_name='Academic Level')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='Icon / Emoji')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('question_count', models.PositiveIntegerField(default=0, verbose_name='Question Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['department', 'level'], name='courses_cou_departm_66b53a_idx'), models.Index(fields=['code'], name='courses_cou_code_612388_idx')],
            },
        ),
    ]
