# Generated by Django 6.0.8 on 2026-08-05 18:16

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('questions', '0001_initial'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('course_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Course Code')),
                ('selected_answer', models.CharField(blank=True, default='', max_length=10, verbose_name='Selected Answer')),
                ('correct_answer', models.CharField(blank=True, default='', max_length=10, verbose_name='Correct Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Time Spent Seconds')),
                ('mode', models.CharField(default='practice', max_length=50, verbose_name='Mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='courses.course')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='questions.question')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_attempts', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Attempt',
                'verbose_name_plural': 'Practice Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_pr_user_id_121097_idx'), models.Index(fields=['question', 'user'], name='practice_pr_questio_a5880f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('course_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Course Code')),
                ('mode', models.CharField(default='practice', max_length=50, verbose_name='Practice Mode')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Correct Answers')),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name='Wrong Answers')),
                ('score_percentage', models.FloatField(default=0.0, verbose_name='Score Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='courses.course')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice Session',
                'verbose_name_plural': 'Practice Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_pr_user_id_b1e8c7_idx'), models.Index(fields=['course', '-created_at'], name='practice_pr_course__6acec2_idx')],
            },
        ),
    ]
