# Generated by Django 6.0.8 on 2026-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Time Spent Seconds'),
        ),
    ]
