# Generated by Django 6.0.8 on 2026-08-05 18:16

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.CharField(default=common.utils.generate_uuid, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Activation Code')),
                ('access_duration', models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('full_time', 'Full Time')], default='full_time', max_length=50, verbose_name='Access Duration')),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='unused', max_length=30, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('assigned_student_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Assigned Student Email')),
                ('assigned_student_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Assigned Student Name')),
                ('date_activated', models.DateTimeField(blank=True, null=True, verbose_name='Activation Date')),
                ('is_sample', models.BooleanField(default=False, verbose_name='Is Sample Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activation Code',
                'verbose_name_plural': 'Activation Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
